/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1080px",
    },
    container: {
      center: true,
    },
    colors: {
      black: "#000",
      white: {
        0: "#FFF",
        50: "#FDFDFD",
        100: "#FBFBFB",
      },
      gray: {
        50: "#F6F6F6",
        100: "#EDF2F7",
        300: "#E2E8F0",
        800: "#2A3644",
        900: "#171923",
      },
      teal: {
        100: "#B2F5EA",
        200: "#81E6D9",
        300: "#4FD1C5",
        400: "#38B2AC",
        500: "#179BA5",
        600: "#117279",
        900: "#1D4044",
      },
      blue: {
        400: "#4CA5DC",
        700: "#2A3644",
        800: "#031617",
        900: "#1F2934",
      },
      green: "#6DC24A",
    },
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      med: "1rem",
      lg: "1.125rem",
      "2xl": "1.5rem",
      "3xl": "2rem",
      "3.5xl": "2.75rem",
      "4xl": "3.125rem",
    },
    textColor: {
      black: "#2A3644",
      teal: "#169AA4",
      gray: {
        200: "#D9D9D9",
        700: "#7F868F",
        800: "#4A5568",
      },
      white: "#FFF",
      blue: "#A0DDE6",
      green: "#6DC24A",
    },
    extend: {
      fontFamily: {
        poppins: ["Poppins", "ui-sans-serif"],
      },
      borderWidth: {
        1: "1px",
      },
      maxWidth: {
        max: "1080px",
        "linked-buttons": "75%",
        hero: "40%",
        "header-text": "80%",
        "repeatable-config-img": "655px",
        rolodex: "465px",
      },
      maxHeight: {
        "repeatable-config-img": "655px",
      },
      minHeight: {
        hero: "775px",
        "hero-text": "200px",
        "mobile-hero-text": "155px",
        "contact-us-arrow": "12px",
      },
      minWidth: {
        "repeatable-config-text-narrow": "290px",
      },
      height: {
        hero: "775px",
        "hero-button": "35px",
        "lets-chat": "150px",
        "lets-chat-small": "60px",
      },
      width: {
        hero: "775px",
        "hero-button": "35px",
        "header-text": "50%",
      },
      margin: {
        "hero-button-arrow": "11px",
        "hero-button": "430px",
      },
      padding: {
        "lets-chat-graphic": "150px",
      },
      lineHeight: {
        display: "64px",
      },
      keyframes: {
        roll: {
          "0%": { transform: "translateY(0)" },
          "10%": { transform: "translateY(-64px)" },
          "20%": { transform: "translateY(-128px)" },
          "30%": { transform: "translateY(-192px)" },
          "40%": { transform: "translateY(-256px)" },
          "50%": { transform: "translateY(-320px)" },
          "60%": { transform: "translateY(-384px)" },
          "70%": { transform: "translateY(-448px)" },
          "80%": { transform: "translateY(-512px)" },
          "90%": { transform: "translateY(-576px)" },
          "100%": { transform: "translateY(-640px)" },
        },
        // reduced motion version of the rolodex animation that still uses the rolodex
        // mechanics but hides the rolling effect
        fade: {
          "4%": { color: "#169AA4" },
          "8%": { transform: "translateY(0)" },
          "9%": { color: "#FDFDFD", transform: "translateY(-64px)" },
          "10%": { color: "#169AA4" },
          "14%": { color: "#169AA4" },
          "18%": { transform: "translateY(-64px)" },
          "19%": { color: "#FDFDFD", transform: "translateY(-128px)" },
          "20%": { color: "#169AA4" },
          "24%": { color: "#169AA4" },
          "28%": { transform: "translateY(-128px)" },
          "29%": { color: "#FDFDFD", transform: "translateY(-192px)" },
          "30%": { color: "#169AA4" },
          "34%": { color: "#169AA4" },
          "38%": { transform: "translateY(-192px)" },
          "39%": { color: "#FDFDFD", transform: "translateY(-256px)" },
          "40%": { color: "#169AA4" },
          "44%": { color: "#169AA4" },
          "48%": { transform: "translateY(-256px)" },
          "49%": { color: "#FDFDFD", transform: "translateY(-320px)" },
          "50%": { color: "#169AA4" },
          "54%": { color: "#169AA4" },
          "58%": { transform: "translateY(-320px)" },
          "59%": { color: "#FDFDFD", transform: "translateY(-384px)" },
          "60%": { color: "#169AA4" },
          "64%": { color: "#169AA4" },
          "68%": { transform: "translateY(-384px)" },
          "69%": { color: "#FDFDFD", transform: "translateY(-448px)" },
          "70%": { color: "#169AA4" },
          "74%": { color: "#169AA4" },
          "78%": { transform: "translateY(-448px)" },
          "79%": { color: "#FDFDFD", transform: "translateY(-512px)" },
          "80%": { color: "#169AA4" },
          "84%": { color: "#169AA4" },
          "88%": { transform: "translateY(-512px)" },
          "89%": { color: "#FDFDFD", transform: "translateY(-576px)" },
          "90%": { color: "#169AA4" },
          "94%": { color: "#169AA4" },
          "98%": { transform: "translateY(-576px)" },
          "99%": { color: "#FDFDFD", transform: "translateY(0px)" },
        },
      },
      animation: {
        rolodex: "roll 20s cubic-bezier(.75,0,.25,1) infinite",
        fadeIn: "fade 20s cubic-bezier(.75,0,.25,1) infinite",
      },
    },
  },
  plugins: [],
};
